import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import "../globals.css";
import { Theme } from "@radix-ui/themes";
import { MainLayout } from "@/components/layout/main-layout/main-layout";
import { cn } from "@/utils/cn";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("antialiased")}>
        <Theme>
          <MainLayout>{children}</MainLayout>
        </Theme>
      </body>
    </html>
  );
}
